### ISSUE TITLE
dockerfile have wrong address

### ISSUE THREAD

**Issue by Dobob1022** [tenstorrent/tt-buda#10]
On the release on v0.9.80.gs.231222. There is the Dockerfile-release.

But in that file, I think the repository is setting into tenstorrent private repository. 

I think it must be changed into working link

File name : Dockerfile-release
`
FROM yyz-gitlab.local.tenstorrent.com~~~~~
`

**Comment by milank94** [comment]
@Dobob1022 The `Dockerfile-release` should be removed from the package. This is an artifact from the build itself.

To access the Docker image, you can use the following command: `docker pull ghcr.io/tenstorrent/tt-buda/gs:v0.9.80.gs.231222`

Be sure to have your Docker registry configured using the following steps: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#docker-container-installation

All Docker packages for TT-Buda are found here: https://github.com/orgs/tenstorrent/packages/container/package/tt-buda%2Fgs

**Comment by Dobob1022** [comment]
![Screenshot 2024-02-29 at 9 35 47 AM](https://github.com/tenstorrent/tt-buda/assets/20010553/fb4811cb-8070-48af-921a-5b190e15d543)
Sorry for late reply. Its working with ghcr.io link!
