### ISSUE TITLE
Package 'clang-6.0' has no installation candidate

### ISSUE THREAD

**Issue by danindiana** [tenstorrent/tt-buda#14]
For: https://docs.tenstorrent.com/tenstorrent/v/tt-buda/installation

where: apt-get install -y build-essential clang-6.0 libhdf5-serial-dev libzmq3-dev

$ sudo apt-get install -y build-essential clang-6.0 libhdf5-serial-dev libzmq3-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libhdf5-dev' instead of 'libhdf5-serial-dev'
Package clang-6.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'clang-6.0' has no installation candidate

OS: Ubuntu 22.04 jammy
 Kernel: x86_64 Linux 6.5.0-21-generic
 Uptime: 5m
 Packages: 1812
 Shell: bash 5.1.16
 Resolution: 2560x1080
 DE: GNOME 42.0
 WM: Mutter
 WM Theme: Adwaita
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11
 Disk: 29G / 1.8T (2%)
 CPU: AMD Ryzen 9 7950X3D 16-Core @ 32x 5.759GHz
 GPU: AMD/ATI
 RAM: 6827MiB / 192419MiB

![Screenshot from 2024-03-07 14-04-20](https://github.com/tenstorrent/tt-buda/assets/3030588/3b4c49d9-374d-466d-822b-e174e1ee5bb1)

Gemini advice:

You're absolutely right! It seems that the `clang-6.0` package isn't directly available in the default Ubuntu 22.04 repositories. Let's fix this and get your installation rolling.

**Here's how to install clang-6.0 on Ubuntu 22.04:**

1. **Add the LLVM Repository:**  The LLVM project provides the necessary packages for Clang. Let's add their repository to our system:

   ```bash
   sudo wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - 
   sudo add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-6.0 main"
   ```

2. **Update Package Lists:** Update the package lists to reflect the newly added repository.
   ```bash
   sudo apt-get update
   ```

3. **Install clang-6.0:** Now you should be able to install the specific version of Clang: 
   ```bash
   sudo apt-get install -y clang-6.0
   ```

**Additional Notes**

* If you need other Clang-related tools, packages like `clang-tools-6.0`, `lld-6.0`, etc., might be useful. Install them similarly.
* You can adjust the `-6.0` part to install a different minor version of Clang 6 if needed.

**Rerun the Installation Command**

Now that you have clang-6.0 installed, try running the backend compiler dependencies installation command again:

```bash
sudo apt-get install -y build-essential clang-6.0 libhdf5-serial-dev libzmq3-dev
```

This should now proceed without any issues.

**Let me know if you encounter any further problems. I'm here to help!**

**Comment by milank94** [comment]
@danindiana the instructions there are for Ubuntu 20.04. 

For Ubuntu 22.04, official support is still in development, but these are the deps you will need:

```
apt update && apt install -y \
    build-essential \
    clang \
    curl \
    libboost-all-dev \
    libgl1-mesa-glx \
    libgoogle-glog-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    python-is-python3 \
    python3-pip \
    python3-venv \
    ruby \
    software-properties-common \
    wget

# Install libyaml
RUN wget http://mirrors.kernel.org/ubuntu/pool/main/y/yaml-cpp/libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb
RUN wget http://mirrors.kernel.org/ubuntu/pool/main/y/yaml-cpp/libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
RUN dpkg -i libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
RUN rm libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
```

**Comment by danindiana** [comment]
Yes, @milank94 you are correct. I noticed my mistake yesterday and re-installed correct Ubuntu (20.04) on the target server. Much better progress! Will close out. 

> @danindiana the instructions there are for Ubuntu 20.04.
> 
> For Ubuntu 22.04, official support is still in development, but these are the deps you will need:
> 
> ```
> apt update && apt install -y \
>     build-essential \
>     clang \
>     curl \
>     libboost-all-dev \
>     libgl1-mesa-glx \
>     libgoogle-glog-dev \
>     libhdf5-serial-dev \
>     libzmq3-dev \
>     python-is-python3 \
>     python3-pip \
>     python3-venv \
>     ruby \
>     software-properties-common \
>     wget
> 
> # Install libyaml
> RUN wget http://mirrors.kernel.org/ubuntu/pool/main/y/yaml-cpp/libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb
> RUN wget http://mirrors.kernel.org/ubuntu/pool/main/y/yaml-cpp/libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
> RUN dpkg -i libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
> RUN rm libyaml-cpp-dev_0.6.2-4ubuntu1_amd64.deb libyaml-cpp0.6_0.6.2-4ubuntu1_amd64.deb
> ```

/
