### ISSUE TITLE
errata in git submodule update

### ISSUE THREAD

**Issue by danindiana** [tenstorrent/tt-buda#15]
For: https://docs.tenstorrent.com/tenstorrent/v/tt-buda/installation#backend-compiler-dependencies

![Screenshot from 2024-03-07 18-47-16](https://github.com/tenstorrent/tt-buda/assets/3030588/83f1c60a-463b-485c-85a0-ac176b3565b8)

git submodule –init –recursive

should be:

git submodule update –init –recursive

**Comment by milank94** [comment]
FYI @adifrancescoTT & @dsklavos

**Comment by danindiana** [comment]
@milank94 
Apologies it's not obviously clear from original post what's at issue. The characters need two dashes rather than one. This error mode is a byproduct of persons attempting to turn up the software stack via copypasta.

git submodule update --init --recursive

**Comment by adifrancescoTT** [comment]
Thanks @danindiana ! I could not see that actually so very helpful call out. Will fix asap.
