### ISSUE TITLE
Invalid C++ API documentation link

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-buda#16]
The C++ BUDA API link is broken. On this page: https://docs.tenstorrent.com/tenstorrent/v/tt-buda/api#c-runtime-api It ponts to https://yyz-webservice-02.local.tenstorrent.com/docs/budabackend-docs/. Which is NX domain.

**Comment by staylorTT** [comment]
Thanks for bringing this to our attention. I will work on getting this fixed.

**Comment by staylorTT** [comment]
We are going through some internal changes to our documentation pipeline and hope to have the backend API reference published by mid June. In the meantime I am seeing if I can get it published before we launch the entire pipeline. Appreciate your patience here.
