### ISSUE TITLE
[Feature request] Display better messaging when moving workload to CPU

### ISSUE THREAD

**Issue by adifrancescoTT** [tenstorrent/tt-buda#31]
Verbatim from Grayskull user:

“Sometimes BUDA ended up going Pytorch/CPU silently. QWEN model for example: it compiled but it was on the CPU and silent, no message about it. Until we tried to debug where it was stuck and that is when we see it is on Pytorch”

**Comment by AleksKnezevic** [comment]
Thanks @adifrancescoTT. Pybuda supports various logging levels, to see fallback messages please use a higher verbosity logging level such as `LOGURU_LEVEL=DEBUG`
