### ISSUE TITLE
Warning `OpType not found in params. Defaulting to nop params.` for OpTypes `sine`, `cosine`, and `abs`

### ISSUE THREAD

**Issue by mvkvc** [tenstorrent/tt-buda#35]
When working to add the Phi-3 model to `tt-buda-demos` in this [PR](https://github.com/tenstorrent/tt-buda-demos/pull/116) I received these warnings in my pipeline which seem to be impacting the results. This is for a `torch` model using `transformers` running on a Grayskull e75 on Ubuntu 20.04. The full code along with the system information can be found in that PR.

Here are the different related warnings shown:

- `2024-07-21 17:48:48.253 | WARNING  | Model           - OpType 'abs' not found in params. Defaulting to nop params.`
- `2024-07-21 17:48:41.827 | WARNING  | Model           - OpType 'cosine' not found in params. Defaulting to nop params.`
- `2024-07-21 17:48:41.827 | WARNING  | Model           - OpType 'sine' not found in params. Defaulting to nop params.`

Any guidance on how to resolve would be appreciated.

**Comment by mvkvc** [comment]
I learned that the balancer performance estimation parameters for those ops [here](https://github.com/tenstorrent/tt-budabackend/blob/main/perf_lib/op_model/params/grayskull/params_v2.yaml) don't exist for Grayskull. The model does take very long to balance so this makes sense. If this is expected behaviour and doesn't affect the model output after compilation I can close.

**Comment by staylorTT** [comment]
@tt-mpantic Please investigate where in the stack these are being raised and if any action needs to be taken.

**Comment by tt-mpantic** [comment]
Hi @mvkvc, 

As you already correctly noted performance estimation parameters are not provided for these ops, hence the warning. Absence of these parameters can affect how BUDA compiler balances and places operations on the chip but if doesn't affect model output.
