### ISSUE TITLE
ImportError: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tyamakawatt** [tenstorrent/tt-buda#36]
I have `libyaml-cpp.so.0.7` installed. When I try to import `pybuda` I see the following error:

```
Traceback (most recent call last):
  File "/home/todd/tt-please/smoke.py", line 2, in <module>
    import pybuda
  File "/home/todd/tt-please/venv/lib/python3.10/site-packages/pybuda/__init__.py", line 42, in <module>
    from .module import Module, PyTorchModule, PyBudaModule, TFModule, TFGraphDefModule, OnnxModule, MXNetModule, JaxModule, TFLiteModule
  File "/home/todd/tt-please/venv/lib/python3.10/site-packages/pybuda/module.py", line 14, in <module>
    from .pybudaglobal import register_module, lazy_trace_data
  File "/home/todd/tt-please/venv/lib/python3.10/site-packages/pybuda/pybudaglobal.py", line 16, in <module>
    from pybuda._C.backend_api import BackendType
ImportError: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory
```

I have 0.7 installed, is there any reason it needs to be 0.6? 
```
lrwxrwxrwx 1 root root 18 Mar 25  2022 /usr/lib/x86_64-linux-gnu/libyaml-cpp.so -> libyaml-cpp.so.0.7
```

**Comment by milank94** [comment]
Hi @tyamakawatt .

Which version of OS are you on? I'm assuming Ubuntu 22.04?

If that is the case, then yes, you need version 0.6. We have instruction in the first 5 steps for downloading the correct version of `libyaml-cpp-dev` based on OS: https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#backend-compiler-dependencies

**Comment by tyamakawatt** [comment]
Hi @milank94, I am on Ubuntu 22.04. When I use the docs you pointed me to, `import pybuda` works now. Thanks for your help.

It looks like the docs linked in the README are out of date so I submitted a PR to update the docs to the link you sent me: https://github.com/tenstorrent/tt-buda/pull/38
