### ISSUE TITLE
Misalignment between Buda releases (tags) and tt-buda source code

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-buda#37]
The releases of Buda are not aligned with the source code in `tt-buda`. This is causing errors when customers and users are trying to build tt-buda from source, but don't actually have the correct source code used for that build.

Need a process or method for ensuring that the source code matches that used to generate the release.

**Comment by staylorTT** [comment]
@AleksKnezevic Is this something we can work with @vmilosevic on to get the latest source code pushed that we used for the release?

**Comment by staylorTT** [comment]
INFO: Is the specific issue here that when you build the source code from main it will then not work with the `tt-buda-demos`. I believe we have tests that ensure it should build at main.  Just trying to narrow down how this is failing to build.

**Comment by AleksKnezevic** [comment]
No, releases are not done off of main, they are done off a branch. Fixes made to that branch for the release also go into main, but it's possible that something else in main introduces a regression on one of the tests.

**Comment by staylorTT** [comment]
We have some fixes that need to be pushed to fix Dual Chip support. Lets have this coincide with those changes and make sure that source will reflect the .whl that will include the Dual Chip fixes.
