### ISSUE TITLE
Add better UI to the API reference page

### ISSUE THREAD

**Issue by sebphem** [tenstorrent/tt-buda#41]
Current documentation:
<img width="364" alt="Screenshot 2024-07-25 at 12 19 04 PM" src="https://github.com/user-attachments/assets/b40d942d-a6c4-4ca7-9bcf-7a4fd00f7ec2">

Suggested change:
<img width="299" alt="Screenshot 2024-07-25 at 12 17 40 PM" src="https://github.com/user-attachments/assets/f7f08516-0337-4a99-81b6-a60613d3a302">

**Comment by staylorTT** [comment]
Thank you for the suggestion we will take this in to account as we build out our new compiler over in https://github.com/tenstorrent/tt-mlir
