### ISSUE TITLE
Add torch.cuda equivalent for buda

### ISSUE THREAD

**Issue by sebphem** [tenstorrent/tt-buda#43]
More specifically, these functions:
torch.cuda.is_avaiable
torch.cuda.temperature
torch.cuda.power_draw
torch.cuda.clock_rate
torch.cuda.device_count

https://pytorch.org/docs/stable/cuda.html

**Comment by staylorTT** [comment]
At this point in time the work required to implement this would not be feasible via our compiler. TT-SMI should be the right place for this type of information.
