### ISSUE TITLE
Huge memory requirement compiling a rather small UNet

### ISSUE THREAD

**Issue by urbste** [tenstorrent/tt-buda#44]
This issue is related to a discussion on discord with Milan Kordic.

I have been trying to compile a Unet with different input shapes: 256x256, 512x512 and 1024x1024.
When compiling the 512x512 model, the compiler uses > 64GB (I even had to increase the system SWAP to 16GB).
For the 1024x1024 model he wants to allocate 1024GB of Ram (which is obiously not feasible).

Milan mentioned to open an issue so it can be tracked.

If you need my code or my model please don't hestiate to ask :)

**Comment by staylorTT** [comment]
Can you please try to set environment flag `PYBUDA_CONVERT_PARAMS_TO_TVM=0` and see if this helps?

**Comment by urbste** [comment]
I tested the UNet with this call and input shape 1024x1024:
`PYBUDA_CONVERT_PARAMS_TO_TVM=0 python test_unet.py`
And I verified in my python script that the env variable ist set:
`print("PYBUDA_CONVERT_PARAMS_TO_TVM: ",os.environ["PYBUDA_CONVERT_PARAMS_TO_TVM"])`

The resource utilization is still huge:
![image](https://github.com/user-attachments/assets/8614f0c6-4397-463e-ab97-8a065f64d6e0)

And then at some point it crashes:
![image](https://github.com/user-attachments/assets/788ecf9f-a4b7-4c21-a227-b2f3eb632cf4)

**Comment by staylorTT** [comment]
Thanks for the follow-up let me have the team take another look and see.
