### ISSUE TITLE
Inference speed of models

### ISSUE THREAD

**Issue by lapinM** [tenstorrent/tt-buda#45]
I tested the launch of the GPT2 inference model on a single N300 chip and achieved some results.
The code was based on this [demo](https://github.com/tenstorrent/tt-buda-demos/blob/main/model_demos/nlp_demos/gpt2/gpt2_text_generation.py).

**As a result, when running on a single chip:**
The text generation speed for the 350M model: 2 seconds per token

Based on [this guide](https://docs.tenstorrent.com/tenstorrent/v/tt-buda/user_guide#quick-start), the code for GPT-2 has been adapted and the generation speed has been achieved: 1 second per token

Is it possible to speed up the model inference?
Could you share the benchmarks for the inference speed of various models?

**Comment by milank94** [comment]
@lapinM benchmarks for Buda are available here: https://github.com/tenstorrent/benchmarking?tab=readme-ov-file#performance-table

The repository is tagged by release so that you can run the benchmarks based on release version.
