### ISSUE TITLE
Dependency Conflict When Installing tt-smi in Environment with Pybuda Already Installed

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-buda#46]
## Description

When installing current tt-smi version within the same python environment where pybuda v0.18.1-rc is already installed a pip dependency conflict occur.

## Reproduce

To reproduce follow the following steps:
1. Scp over zip version of the release.
2. Unzip zip files.
3. Create the python env
```bash
python3 -m venv python_env
source python_env/bin/activate
pip install -U pip
```
4. Pip install the whl files within the environment
5. Then install tt-smi using instruction within the tt-smi repository README. 

## Observed behavior

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flax 0.6.0 requires rich~=11.1, but you have rich 13.7.0 which is incompatible.
pybuda 0.1.240703+dev.gs.c2d0102 requires requests==2.28.2, but you have requests 2.32.0 which is incompatible.
```

## Expected behavior

No pip dependencies errors and a successful install of both pybuda and tt-smi within the same python virtual environment

**Comment by staylorTT** [comment]
For our next release lets update these versions to see if it causes any issues.

**Comment by jserbedzijaTT** [comment]
Should be resolved in the latest main.
