### ISSUE TITLE
Increase in compilation times with newer releases

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-buda#47]
There is a noticeable increase in the compilation time of models with newer pybuda releases.

For example (BERT-Large w/ 384 input size):
| Release Version | Release Date | Compilation Time (s) | Performance (sen/s) |
|-----------------|--------------|----------------------|---------------------|
| v0.9.80         | Jan 5, 2024  | 117.7                | 65                  |
| v0.12.3         | May 10, 2024 | 261.8                | 114                 |
| v0.18.2         | Jul 18, 2024 | 358.4                | 118                 |

That is a 3x increase in compilation time.

Some models have been reported to take even longer going from 5min -> 60min.

**Comment by staylorTT** [comment]
We will monitor this for now for severity.
