### ISSUE TITLE
Gigabyte ai top style software 

### ISSUE THREAD

**Issue by Isaina** [tenstorrent/tt-buda#48]
Hi can you add software like gigabyte top ai utility to fine tuning models so we can use hardware in research for normal peoples 

https://www.gigabyte.com/Press/News/2201

**Comment by milank94** [comment]
Thanks for the suggestion @Isaina. This is a feature we can consider in our upcoming MLIR project.

CC: @staylorTT

**Comment by Isaina** [comment]
Also if is possible to make one kit like external GPUs for macOS thru thunderbird port so we can use tensortorrent hardware thru usb 4.0 port

**Comment by milank94** [comment]
> Also if is possible to make one kit like external GPUs for macOS thru thunderbird port so we can use tensortorrent hardware thru usb 4.0 port

Noted as well. CC: @KarmaPoliceT2

**Comment by JushBJJ** [comment]
+1 on this

eGPUs wont work on ARM Macs so you would have to wait for Asahi Linux to support Thunderbolt 4. @Isaina @milank94 

Ironically, i've installed asahi on my m1 macbook last month in advance for this use-case

**Comment by Isaina** [comment]
Yes MacOs is just one platform but support also for windows and Linux on x86 with egpu module would be great

**Comment by KarmaPoliceT2** [comment]
Ok, so let's say we were planning to do an eGPU, which I definitely don't want to commit Tenstorrent to or give any indication of an imminent release. But let's say we wanted to do it. 

What specs would you want the module to have, rough form factor, power, cooling noise levels, and connectivity (you mention [TB4)](url) would be fantastic to understand.

We've actually kicked this idea around internally for a long time but not been able to pull the trigger. If I can narrow down the definition of what y'all would like to see in an egpu-like solution maybe I can finally get it spun up as an actual project around here.

**Comment by Isaina** [comment]
For me cooling is no issue can be a little noisy but price need to be good because such card would be old in one or two yrs and also support for lm studio so we can connect egpu and use it https://lmstudio.ai/blog/lmstudio-v0.3.0

**Comment by Isaina** [comment]
Can you also offer card in 500 usd price range but with 32 64 or 128 go vram because vram is major stopper for largger usable models
