### ISSUE TITLE
Where I can get the principle/algorithms of place and route？

### ISSUE THREAD

**Issue by MbjYjbpivj** [tenstorrent/tt-buda#49]
What are the principles and algorithms for partitioning subgraphs and routing? Where can I find reference materials?

**Comment by milank94** [comment]
@MbjYjbpivj -- checkout our TT-Buda docs for reference material: https://docs.tenstorrent.com/pybuda/latest/advanced_user_guide.html#

There are some more details on configuration and placement: https://docs.tenstorrent.com/pybuda/latest/api.html#configuration-and-placement
