### ISSUE TITLE
The source code of tt-buda compiler

### ISSUE THREAD

**Issue by dodohack** [tenstorrent/tt-buda#5]
From the repository of tt-buda, I can only find the model demo and precompiled PyBUDA/TVM binaries.

Do you have intention to open source the tt-buda and TVM compilers?

**Comment by milank94** [comment]
Thank you for your inquiry @dodohack.

In the short-term, we will only be providing the precompiled binaries for TT-Buda, along with the model demos. 

For an open-source alternative, please checkout the TT-Metalium stack: https://github.com/tenstorrent-metal/tt-metal

**Comment by milank94** [comment]
Closing issue as the questions has been answered / resolved: https://github.com/tenstorrent/tt-buda/issues/5#issuecomment-1880197734
