### ISSUE TITLE
TT-Buda Installation Failed 

### ISSUE THREAD

**Issue by OwenKZ** [tenstorrent/tt-buda#55]
Hello, I am new here and I would like to try TT-Buda and Pybuda flow for my research.I wonder can I use the compilation tools for tests if I don't have a real tt-device?

I failed the installation when I first follow [tt-buda-install](https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md). And while I followed "Setup HugePages" and tried to run `sudo -E python3 setup_hugepages.py first_pass`, It shows Assertion ERROR that `Did not find any tt devices.`

I have used tools like TVM and it can compile the DNN network into JSON or other forms for my own accelerator when I give TVM the description of it. Therefore, I wonder how to use TT-BUDA and Pybuda without the real tt-device? Or is there any step wrong in my description?

Thanks!

**Comment by milank94** [comment]
Hi @OwenKZ -- you can run some examples through `pybuda` using what we call "Golden".

For installation, you can skip the Hugepages step as that is only required when physical devices are present.

These would be the steps to follow:
* https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#backend-compiler-dependencies
* https://github.com/tenstorrent/tt-buda-demos/blob/main/first_5_steps/1_install_tt_buda.md#pybuda-installation

After you have an environment with a version of `pybuda` installed, you can try running in "Golden".d.

As an example of this, refer to the example file here: https://github.com/tenstorrent/tt-buda/blob/main/first_5_steps/2_running_nlp_models.ipynb

On **Step 5: Instantiate Tenstorrent device**, you can add a parameter to `TTDevice` which sets the target backend to be Golden.

```python
tt0 = pybuda.TTDevice(
    name="tt_device_0",  # here we can give our device any name we wish, for tracking purposes
    arch=pybuda.BackendDevice.Grayskull,  # we set the target device architecture to compile for
    devtype=pybuda.BackendType.Golden  # we set the target backend type to be Golden for running off device
)
```

**Comment by OwenKZ** [comment]
Now it works fine! Thanks ~
